# Generated by Django 5.2.8 on 2025-11-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChamCong',
            fields=[
                ('machamcong', models.AutoField(primary_key=True, serialize=False)),
                ('manhanvien', models.IntegerField()),
                ('ngaylam', models.DateField()),
                ('giovao', models.TimeField()),
                ('giora', models.TimeField(blank=True, null=True)),
                ('ghichu', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CHAMCONG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HopDong',
            fields=[
                ('mahopdonglaodong', models.AutoField(primary_key=True, serialize=False)),
                ('manhanvien', models.IntegerField()),
                ('loaihopdong', models.CharField(max_length=50)),
                ('ngaybatdau', models.DateField()),
                ('ngayketthuc', models.DateField(blank=True, null=True)),
                ('luongcoban', models.DecimalField(decimal_places=2, max_digits=18)),
                ('phucap', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ghichu', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'HOPDONG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('manhanvien', models.AutoField(primary_key=True, serialize=False)),
                ('hoten', models.CharField(max_length=100)),
                ('vaitro', models.CharField(blank=True, max_length=50, null=True)),
                ('sdt', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('diachi', models.CharField(blank=True, max_length=200, null=True)),
                ('luong', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ngayvaolam', models.DateField(blank=True, null=True)),
                ('calam', models.CharField(blank=True, max_length=50, null=True)),
                ('ghichu', models.TextField(blank=True, null=True)),
                ('trangthai', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'NHANVIEN',
                'managed': False,
            },
        ),
    ]
