# Generated by Django 5.2.8 on 2025-11-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('mathongbao', models.AutoField(primary_key=True, serialize=False)),
                ('tieude', models.CharField(max_length=200)),
                ('noidung', models.TextField()),
                ('nguoigui', models.IntegerField()),
                ('ngaygui', models.DateTimeField()),
            ],
            options={
                'db_table': 'THONGBAO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThongBaoNhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mathongbao', models.IntegerField()),
                ('mataikhoan', models.IntegerField()),
                ('ngaydoc', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'THONGBAO_NHANVIEN',
                'managed': False,
            },
        ),
    ]
