# Generated by Django 5.2.8 on 2025-11-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mataikhoan', models.AutoField(primary_key=True, serialize=False)),
                ('tendangnhap', models.CharField(max_length=50, unique=True)),
                ('manhanvien', models.IntegerField()),
                ('vaitro', models.CharField(choices=[('QUANLY', 'Quản lý'), ('NHANVIEN', 'Nhân viên')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'TAIKHOAN',
                'managed': False,
            },
        ),
    ]
