# Generated by Django 5.2.8 on 2025-11-28 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CongTacVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=150)),
                ('sdt', models.CharField(blank=True, max_length=20, null=True)),
                ('zalo', models.CharField(blank=True, max_length=20, null=True)),
                ('ghichu', models.TextField(blank=True, null=True)),
                ('ngunghop', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=150)),
                ('dongia', models.DecimalField(decimal_places=0, max_digits=12)),
                ('donvi', models.CharField(max_length=50)),
                ('ngung', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=150)),
                ('cccd', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('sodt', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('diachi', models.CharField(blank=True, max_length=255, null=True)),
                ('ngunghd', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiPhong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('mota', models.TextField(blank=True, null=True)),
                ('giacoban', models.DecimalField(decimal_places=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=150)),
                ('chucvu', models.CharField(max_length=50)),
                ('sodt', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('taikhoan', models.CharField(max_length=50, unique=True)),
                ('matkhau', models.CharField(max_length=255)),
                ('ngunghd', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DatPhong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaikhach', models.CharField(max_length=50)),
                ('ngaynhan', models.DateField()),
                ('ngaytra', models.DateField()),
                ('trangthai', models.CharField(choices=[('CHO', 'Chờ'), ('XAC_NHAN', 'Xác nhận'), ('DANG_O', 'Đang ở'), ('HOAN_TAT', 'Hoàn tất'), ('HUY', 'Hủy')], default='CHO', max_length=20)),
                ('ghichu', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ctv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.congtacvien')),
                ('khach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.khachhang')),
                ('nhanvien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaylap', models.DateTimeField(auto_now_add=True)),
                ('tongtien', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('trangthai', models.CharField(choices=[('CHUA', 'Chưa thanh toán'), ('DA', 'Đã thanh toán'), ('HUY', 'Hủy')], default='CHUA', max_length=10)),
                ('datphong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.datphong')),
                ('khach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='CT_HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(max_length=50)),
                ('mathamchieu', models.IntegerField(blank=True, null=True)),
                ('mota', models.CharField(blank=True, max_length=255, null=True)),
                ('soluong', models.IntegerField(default=1)),
                ('dongia', models.DecimalField(decimal_places=0, max_digits=12)),
                ('hoadon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chitiet', to='quanly.hoadon')),
            ],
        ),
        migrations.CreateModel(
            name='ChamCong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField()),
                ('trangthai', models.CharField(max_length=20)),
                ('sogio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nhanvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoigian', models.DateTimeField(auto_now_add=True)),
                ('hanhdong', models.CharField(max_length=255)),
                ('bang', models.CharField(max_length=100)),
                ('khoachinh', models.CharField(max_length=100)),
                ('noidung', models.TextField()),
                ('manv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sophong', models.CharField(max_length=10, unique=True)),
                ('trangthai', models.CharField(choices=[('TRONG', 'Trống'), ('DANG_THUE', 'Đang thuê'), ('BAO_TRI', 'Đang bảo trì')], default='TRONG', max_length=20)),
                ('ngungkdd', models.BooleanField(default=False)),
                ('loai', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.loaiphong')),
            ],
        ),
        migrations.CreateModel(
            name='DoiNha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaytao', models.DateTimeField(auto_now_add=True)),
                ('trangthai', models.CharField(choices=[('CANDON', 'Cần dọn'), ('DANGDON', 'Đang dọn'), ('DADON', 'Đã dọn')], default='CANDON', max_length=20)),
                ('ghichu', models.TextField(blank=True, null=True)),
                ('nhanvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.nhanvien')),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.phong')),
            ],
        ),
        migrations.CreateModel(
            name='CT_DatPhong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giaphong', models.DecimalField(decimal_places=0, max_digits=12)),
                ('datphong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chitiet', to='quanly.datphong')),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.phong')),
            ],
        ),
    ]
