# Generated by Django 5.2.8 on 2025-11-29 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'verbose_name': 'Nhật ký', 'verbose_name_plural': 'Nhật ký'},
        ),
        migrations.AlterModelOptions(
            name='chamcong',
            options={'verbose_name': 'Chấm công', 'verbose_name_plural': 'Chấm công'},
        ),
        migrations.AlterModelOptions(
            name='congtacvien',
            options={'verbose_name': 'Cộng tác viên', 'verbose_name_plural': 'Cộng tác viên'},
        ),
        migrations.AlterModelOptions(
            name='ct_datphong',
            options={'verbose_name': 'Chi tiết đặt phòng', 'verbose_name_plural': 'Chi tiết đặt phòng'},
        ),
        migrations.AlterModelOptions(
            name='ct_hoadon',
            options={'verbose_name': 'Chi tiết hóa đơn', 'verbose_name_plural': 'Chi tiết hóa đơn'},
        ),
        migrations.AlterModelOptions(
            name='datphong',
            options={'verbose_name': 'Đặt phòng', 'verbose_name_plural': 'Đặt phòng'},
        ),
        migrations.AlterModelOptions(
            name='dichvu',
            options={'verbose_name': 'Dịch vụ', 'verbose_name_plural': 'Dịch vụ'},
        ),
        migrations.AlterModelOptions(
            name='doinha',
            options={'verbose_name': 'Dội nhà', 'verbose_name_plural': 'Dội nhà'},
        ),
        migrations.AlterModelOptions(
            name='hoadon',
            options={'verbose_name': 'Hóa đơn', 'verbose_name_plural': 'Hóa đơn'},
        ),
        migrations.AlterModelOptions(
            name='khachhang',
            options={'verbose_name': 'Khách hàng', 'verbose_name_plural': 'Khách hàng'},
        ),
        migrations.AlterModelOptions(
            name='loaiphong',
            options={'verbose_name': 'Loại phòng', 'verbose_name_plural': 'Loại phòng'},
        ),
        migrations.AlterModelOptions(
            name='nhanvien',
            options={'verbose_name': 'Nhân viên', 'verbose_name_plural': 'Nhân viên'},
        ),
        migrations.AlterModelOptions(
            name='phong',
            options={'ordering': ['sophong'], 'verbose_name': 'Phòng', 'verbose_name_plural': 'Phòng'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='bang',
            field=models.CharField(db_column='Bang', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='hanhdong',
            field=models.CharField(db_column='HanhDong', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='khoachinh',
            field=models.CharField(db_column='KhoaChinh', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='manv',
            field=models.ForeignKey(db_column='MaNV', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.nhanvien'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='noidung',
            field=models.TextField(db_column='NoiDung'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='thoigian',
            field=models.DateTimeField(auto_now_add=True, db_column='ThoiGian'),
        ),
        migrations.AlterField(
            model_name='chamcong',
            name='ngay',
            field=models.DateField(db_column='Ngay'),
        ),
        migrations.AlterField(
            model_name='chamcong',
            name='nhanvien',
            field=models.ForeignKey(db_column='MaNV', on_delete=django.db.models.deletion.CASCADE, to='quanly.nhanvien'),
        ),
        migrations.AlterField(
            model_name='chamcong',
            name='sogio',
            field=models.DecimalField(blank=True, db_column='SoGio', decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='chamcong',
            name='trangthai',
            field=models.CharField(db_column='TrangThai', max_length=20),
        ),
        migrations.AlterField(
            model_name='congtacvien',
            name='ghichu',
            field=models.TextField(blank=True, db_column='GhiChu', null=True),
        ),
        migrations.AlterField(
            model_name='congtacvien',
            name='hoten',
            field=models.CharField(db_column='HoTen', max_length=150),
        ),
        migrations.AlterField(
            model_name='congtacvien',
            name='ngunghop',
            field=models.BooleanField(db_column='NgungHopTac', default=False),
        ),
        migrations.AlterField(
            model_name='congtacvien',
            name='sdt',
            field=models.CharField(blank=True, db_column='SDT', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='congtacvien',
            name='zalo',
            field=models.CharField(blank=True, db_column='Zalo', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ct_datphong',
            name='datphong',
            field=models.ForeignKey(db_column='MaDP', on_delete=django.db.models.deletion.CASCADE, related_name='chitiet', to='quanly.datphong'),
        ),
        migrations.AlterField(
            model_name='ct_datphong',
            name='giaphong',
            field=models.DecimalField(db_column='GiaPhong', decimal_places=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='ct_datphong',
            name='phong',
            field=models.ForeignKey(db_column='MaPhong', on_delete=django.db.models.deletion.PROTECT, to='quanly.phong'),
        ),
        migrations.AlterField(
            model_name='ct_hoadon',
            name='dongia',
            field=models.DecimalField(db_column='DonGia', decimal_places=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='ct_hoadon',
            name='hoadon',
            field=models.ForeignKey(db_column='MaHD', on_delete=django.db.models.deletion.CASCADE, related_name='chitiet', to='quanly.hoadon'),
        ),
        migrations.AlterField(
            model_name='ct_hoadon',
            name='loai',
            field=models.CharField(db_column='Loai', max_length=50),
        ),
        migrations.AlterField(
            model_name='ct_hoadon',
            name='mathamchieu',
            field=models.IntegerField(blank=True, db_column='MaThamChieu', null=True),
        ),
        migrations.AlterField(
            model_name='ct_hoadon',
            name='mota',
            field=models.CharField(blank=True, db_column='MoTa', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ct_hoadon',
            name='soluong',
            field=models.IntegerField(db_column='SoLuong', default=1),
        ),
        migrations.AlterField(
            model_name='datphong',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='Created_at'),
        ),
        migrations.AlterField(
            model_name='datphong',
            name='ctv',
            field=models.ForeignKey(blank=True, db_column='MaCTV', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.congtacvien'),
        ),
        migrations.AlterField(
            model_name='datphong',
            name='ghichu',
            field=models.TextField(blank=True, db_column='GhiChu', null=True),
        ),
        migrations.AlterField(
            model_name='datphong',
            name='khach',
            field=models.ForeignKey(db_column='MaKH', on_delete=django.db.models.deletion.PROTECT, related_name='datphongs', to='quanly.khachhang'),
        ),
        migrations.AlterField(
            model_name='datphong',
            name='loaikhach',
            field=models.CharField(db_column='LoaiKhach', max_length=50),
        ),
        migrations.AlterField(
            model_name='datphong',
            name='ngaynhan',
            field=models.DateField(db_column='NgayNhan'),
        ),
        migrations.AlterField(
            model_name='datphong',
            name='ngaytra',
            field=models.DateField(db_column='NgayTra'),
        ),
        migrations.AlterField(
            model_name='datphong',
            name='nhanvien',
            field=models.ForeignKey(db_column='MaNV', on_delete=django.db.models.deletion.PROTECT, related_name='datphongs', to='quanly.nhanvien'),
        ),
        migrations.AlterField(
            model_name='datphong',
            name='trangthai',
            field=models.CharField(choices=[('CHO', 'Chờ'), ('XAC_NHAN', 'Xác nhận'), ('DANG_O', 'Đang ở'), ('HOAN_TAT', 'Hoàn tất'), ('HUY', 'Hủy')], db_column='TrangThai', default='CHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='dichvu',
            name='dongia',
            field=models.DecimalField(db_column='DonGia', decimal_places=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='dichvu',
            name='donvi',
            field=models.CharField(db_column='DonVi', max_length=50),
        ),
        migrations.AlterField(
            model_name='dichvu',
            name='ngung',
            field=models.BooleanField(db_column='NgungCungCap', default=False),
        ),
        migrations.AlterField(
            model_name='dichvu',
            name='ten',
            field=models.CharField(db_column='TenDV', max_length=150),
        ),
        migrations.AlterField(
            model_name='doinha',
            name='ghichu',
            field=models.TextField(blank=True, db_column='GhiChu', null=True),
        ),
        migrations.AlterField(
            model_name='doinha',
            name='ngaytao',
            field=models.DateTimeField(auto_now_add=True, db_column='NgayTao'),
        ),
        migrations.AlterField(
            model_name='doinha',
            name='nhanvien',
            field=models.ForeignKey(db_column='MaNV', on_delete=django.db.models.deletion.CASCADE, to='quanly.nhanvien'),
        ),
        migrations.AlterField(
            model_name='doinha',
            name='phong',
            field=models.ForeignKey(db_column='MaPhong', on_delete=django.db.models.deletion.CASCADE, to='quanly.phong'),
        ),
        migrations.AlterField(
            model_name='doinha',
            name='trangthai',
            field=models.CharField(choices=[('CANDON', 'Cần dọn'), ('DANGDON', 'Đang dọn'), ('DADON', 'Đã dọn')], db_column='TrangThai', default='CANDON', max_length=20),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='datphong',
            field=models.ForeignKey(blank=True, db_column='MaDP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoadons', to='quanly.datphong'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='khach',
            field=models.ForeignKey(db_column='MaKH', on_delete=django.db.models.deletion.PROTECT, related_name='hoadons', to='quanly.khachhang'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='ngaylap',
            field=models.DateTimeField(auto_now_add=True, db_column='NgayLap'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='tongtien',
            field=models.DecimalField(db_column='TongTien', decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='trangthai',
            field=models.CharField(choices=[('CHUA', 'Chưa thanh toán'), ('DA', 'Đã thanh toán'), ('HUY', 'Hủy')], db_column='TrangThai', default='CHUA', max_length=10),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='cccd',
            field=models.CharField(blank=True, db_column='CCCD', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='diachi',
            field=models.CharField(blank=True, db_column='DiaChi', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='email',
            field=models.EmailField(blank=True, db_column='Email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='hoten',
            field=models.CharField(db_column='HoTen', max_length=150),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='ngunghd',
            field=models.BooleanField(db_column='NgungHoatDong', default=False),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='sodt',
            field=models.CharField(blank=True, db_column='SoDT', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loaiphong',
            name='giacoban',
            field=models.DecimalField(db_column='GiaCoBan', decimal_places=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='loaiphong',
            name='mota',
            field=models.TextField(blank=True, db_column='MoTa', null=True),
        ),
        migrations.AlterField(
            model_name='loaiphong',
            name='ten',
            field=models.CharField(db_column='TenLoai', max_length=100),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='chucvu',
            field=models.CharField(db_column='ChucVu', max_length=50),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='email',
            field=models.EmailField(blank=True, db_column='Email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='hoten',
            field=models.CharField(db_column='HoTen', max_length=150),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='matkhau',
            field=models.CharField(db_column='MatKhau', max_length=255),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='ngunghd',
            field=models.BooleanField(db_column='NgungHoatDong', default=False),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='sodt',
            field=models.CharField(blank=True, db_column='SoDT', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='taikhoan',
            field=models.CharField(db_column='TaiKhoan', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='phong',
            name='loai',
            field=models.ForeignKey(db_column='MaLoai', on_delete=django.db.models.deletion.PROTECT, related_name='phongs', to='quanly.loaiphong'),
        ),
        migrations.AlterField(
            model_name='phong',
            name='ngungkdd',
            field=models.BooleanField(db_column='NgungKinhDoanh', default=False),
        ),
        migrations.AlterField(
            model_name='phong',
            name='sophong',
            field=models.CharField(db_column='SoPhong', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='phong',
            name='trangthai',
            field=models.CharField(choices=[('TRONG', 'Trống'), ('DANG_THUE', 'Đang thuê'), ('BAO_TRI', 'Đang bảo trì')], db_column='TrangThai', default='TRONG', max_length=20),
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='AuditLog',
        ),
        migrations.AlterModelTable(
            name='chamcong',
            table='ChamCong',
        ),
        migrations.AlterModelTable(
            name='congtacvien',
            table='CongTacVien',
        ),
        migrations.AlterModelTable(
            name='ct_datphong',
            table='CT_DatPhong',
        ),
        migrations.AlterModelTable(
            name='ct_hoadon',
            table='CT_HoaDon',
        ),
        migrations.AlterModelTable(
            name='datphong',
            table='DatPhong',
        ),
        migrations.AlterModelTable(
            name='dichvu',
            table='DichVu',
        ),
        migrations.AlterModelTable(
            name='doinha',
            table='DoiNha',
        ),
        migrations.AlterModelTable(
            name='hoadon',
            table='HoaDon',
        ),
        migrations.AlterModelTable(
            name='khachhang',
            table='KhachHang',
        ),
        migrations.AlterModelTable(
            name='loaiphong',
            table='LoaiPhong',
        ),
        migrations.AlterModelTable(
            name='nhanvien',
            table='NhanVien',
        ),
        migrations.AlterModelTable(
            name='phong',
            table='Phong',
        ),
    ]
