# Generated by Django 5.2.8 on 2025-11-30 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0002_alter_auditlog_options_alter_chamcong_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'managed': False, 'verbose_name': 'Nhật ký', 'verbose_name_plural': 'Nhật ký'},
        ),
        migrations.AlterModelOptions(
            name='chamcong',
            options={'managed': False, 'verbose_name': 'Chấm công', 'verbose_name_plural': 'Chấm công'},
        ),
        migrations.AlterModelOptions(
            name='congtacvien',
            options={'managed': False, 'verbose_name': 'Cộng tác viên', 'verbose_name_plural': 'Cộng tác viên'},
        ),
        migrations.AlterModelOptions(
            name='ct_datphong',
            options={'managed': False, 'verbose_name': 'Chi tiết đặt phòng', 'verbose_name_plural': 'Chi tiết đặt phòng'},
        ),
        migrations.AlterModelOptions(
            name='ct_hoadon',
            options={'managed': False, 'verbose_name': 'Chi tiết hóa đơn', 'verbose_name_plural': 'Chi tiết hóa đơn'},
        ),
        migrations.AlterModelOptions(
            name='datphong',
            options={'managed': False, 'verbose_name': 'Đặt phòng', 'verbose_name_plural': 'Đặt phòng'},
        ),
        migrations.AlterModelOptions(
            name='dichvu',
            options={'managed': False, 'verbose_name': 'Dịch vụ', 'verbose_name_plural': 'Dịch vụ'},
        ),
        migrations.AlterModelOptions(
            name='doinha',
            options={'managed': False, 'verbose_name': 'Dội nhà', 'verbose_name_plural': 'Dội nhà'},
        ),
        migrations.AlterModelOptions(
            name='hoadon',
            options={'managed': False, 'verbose_name': 'Hóa đơn', 'verbose_name_plural': 'Hóa đơn'},
        ),
        migrations.AlterModelOptions(
            name='khachhang',
            options={'managed': False, 'verbose_name': 'Khách hàng', 'verbose_name_plural': 'Khách hàng'},
        ),
        migrations.AlterModelOptions(
            name='loaiphong',
            options={'managed': False, 'verbose_name': 'Loại phòng', 'verbose_name_plural': 'Loại phòng'},
        ),
        migrations.AlterModelOptions(
            name='nhanvien',
            options={'managed': False, 'verbose_name': 'Nhân viên', 'verbose_name_plural': 'Nhân viên'},
        ),
        migrations.AlterModelOptions(
            name='phong',
            options={'managed': False, 'ordering': ['sophong'], 'verbose_name': 'Phòng', 'verbose_name_plural': 'Phòng'},
        ),
    ]
