# Generated by Django 5.2.8 on 2025-11-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('mahoadon', models.IntegerField(primary_key=True, serialize=False)),
                ('madichvu', models.IntegerField()),
                ('soluong', models.IntegerField()),
                ('dongia', models.DecimalField(decimal_places=2, max_digits=18)),
                ('thanhtien', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ghichu', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CHITIETHOADON',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatPhong',
            fields=[
                ('madatphong', models.AutoField(primary_key=True, serialize=False)),
                ('makhachhang', models.IntegerField()),
                ('maphong', models.IntegerField()),
                ('manhanvien', models.IntegerField()),
                ('ngaydat', models.DateTimeField()),
                ('ngaynhan', models.DateTimeField(blank=True, null=True)),
                ('ngaytra', models.DateTimeField(blank=True, null=True)),
                ('tiendatcoc', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('mahoadon', models.IntegerField(blank=True, null=True)),
                ('ngaylaphoadon', models.DateTimeField(blank=True, null=True)),
                ('tongtien', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ghichu', models.TextField(blank=True, null=True)),
                ('makhuyenmai', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DATPHONG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('madichvu', models.AutoField(primary_key=True, serialize=False)),
                ('tendichvu', models.CharField(max_length=100)),
                ('loaidichvu', models.CharField(blank=True, max_length=50, null=True)),
                ('dongia', models.DecimalField(decimal_places=2, max_digits=18)),
                ('donvi', models.CharField(blank=True, max_length=20, null=True)),
                ('mota', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DICHVU',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('makhachhang', models.AutoField(primary_key=True, serialize=False)),
                ('hoten', models.CharField(max_length=100)),
                ('cccd', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('sdt', models.CharField(blank=True, max_length=15, null=True)),
                ('loaikhach', models.CharField(blank=True, max_length=50, null=True)),
                ('quoctich', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'KHACHHANG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('maphong', models.AutoField(primary_key=True, serialize=False)),
                ('loaiphong', models.CharField(max_length=50)),
                ('giaphong', models.DecimalField(decimal_places=2, max_digits=18)),
                ('trangthai', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'PHONG',
                'managed': False,
            },
        ),
    ]
